### ISSUE TITLE
--mobile flag

### ISSUE THREAD

**Issue by maytis** [angular/mobile-toolkit#108] opened 2016-10-10 04:59 UTC
I'm using the angular-cli: 1.0.0-beta.16. Mobile flag is still disabled. When can we expect the support for mobile flag.

**Comment by ruedagato** [comment] 2016-10-10 06:03
+1

**Comment by chimon2000** [comment] 2016-10-13 01:47
@maytis I have found that `ng init --mobile` works if you've already created the project folder.

**Comment by friedger** [comment] 2016-10-19 22:41
Don't try ng init --mobile
https://github.com/angular/angular-cli/issues/2679

**Comment by michaeljota** [comment] 2016-10-20 12:59
@friedger that issue appears to be fixed and closed. Have not test it.

**Comment by friedger** [comment] 2016-10-20 20:07
@michaeljota The resolution of the issue that an error is thrown if you use the --mobile flag

**Comment by michaeljota** [comment] 2016-10-21 00:42
@friedger Oh! Thanks...

**Comment by agalazis** [comment] 2016-10-22 21:41
still not enabled although the cause was fixed(universal uses 2.0.0 now)

**Comment by elekzalan** [comment] 2016-10-24 07:43
@agalazis Moreover, universal supports aot compilation since it's 2.1.0-rc.1 release. The `--mobile` flag is a must-have for a bunch of projects...

**Comment by born2net** [comment] 2016-11-13 03:23
its broken due to the fact universal is being added with modules.
however, I really don't like universal, I wish we could have an AOT version of this project (no universal)

**Comment by iansim** [comment] 2016-11-17 10:38
without --mobile does angular worth to learn?

**Comment by worldspawn** [comment] 2016-11-23 01:37
Checked on this mobile stuff like a year ago and it had a great bug (something to do with universal) that produced blank templates or a template with the word "null" in it. A year later and now its just disabled, effectively disabling this entire project?!? Ng eco-system feels like an endless chore of beta-never-gets-released-ware. I know, i know, its open source free ware but shit, i'm going to whinge anyway :P

**Comment by webmaxru** [comment] 2016-11-23 09:34
CLI and `--mobile` are just helpers. You can use Mobile Toolkit separately: https://github.com/angular/mobile-toolkit/issues/115#issuecomment-262467713

**Comment by gdi2290** [comment] 2016-11-23 15:14
here's a repo with module packages https://github.com/webmaxru/pwa-guide-ngpoland/tree/step-dashboard

**Comment by sebastianovide** [comment] 2017-01-07 00:26
i've just started a PWA with angular2. In the https://angular.io/ there is a big invitation to try @angular/material. https://material.angular.io/guide/getting-started instructs to use angular-cli but https://github.com/angular/angular-cli has disabled --mobile. Also  https://mobile.angular.io/ indicates to use angular-cli.

The previous link is a nice demo done by @gdi2290 (thanks) but as it is not using the tools suggested by the official documentation, using it as a starting point seems risky. Where are we going to get support from ?

mobile-toolkit seems very quiet (https://github.com/angular/mobile-toolkit/pulse/monthly) and angular-cli position about --mobile is not clear https://github.com/angular/angular-cli/issues/2228

So starting today a new PWA using angular2 seems very painful as there is not official working documentation on how to do it. 

Should we hold before using angular2 for PWA ?

**Comment by hansl** [comment] 2017-01-09 18:15
@alxhub It would be nice to remove any mention of the cli and `--mobile` from the microsite. I think this issue can be either replaced by a new issue for removing the tutorial, or considered for tracking removing the tutorial.

**Comment by Charlkie14** [comment] 2017-01-26 11:03
@sebastianovide 
> Should we hold before using angular2 for PWA ?

I'm still wondering if we should wait on creating pwa with Angular?

**Comment by friedger** [comment] 2017-01-26 11:28
@Charlkie14 Definitively, build PWAs with Angular, this should not depend on the tools!

**Comment by Charlkie14** [comment] 2017-01-26 11:29
Yes your right @friedger. :) I'm trying it out now.

**Comment by sebastianovide** [comment] 2017-02-06 21:57
@Charlkie14  I'm using angular for PWA. Check out ionic2.

**Comment by cre8** [comment] 2017-02-07 10:10
@Charlkie14 ionic2 is similar to PWAs, but it's not the same. Ionic is building an app for the smartphones, PWAs don't need to be packed up to work on different mobile platforms.

**Comment by sebastianovide** [comment] 2017-02-07 20:40
@cre8. Actually I'm building a PWA with Ionic2. Pure PWA with service woker without Phonegap. In us part of ionic2 out of the box.

**Comment by jakeNiemiec** [comment] 2017-03-10 16:57
@sebastianovide very good to know. Can ionic2 do AoT now?

**Comment by mgechev** [comment] 2017-03-15 00:49
I believe we can close this issue. Here's the PR by @alxhub https://github.com/angular/angular-cli/commit/cb2e418 to the CLI.

**Closed by mgechev** 2017-03-15 00:49 UTC
